{
  "previous": "%UCOV9DLycl7tgm0x7i4B0KBDyWtD3Y4jvlZTGMDUDjI=.sha256",
  "author": "@+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519",
  "sequence": 9070,
  "timestamp": 1551291962509,
  "hash": "sha256",
  "content": {
    "type": "post",
    "root": "%I6FaCzdXcKAiZp0LVhwVluDeDkhNPGQXEqNEkUFLq34=.sha256",
    "branch": "%cWf63Qaq+b6V7OK6+LNOS/5LL7JuIerZPR4x6Vevpgw=.sha256",
    "text": "[@ev](@8Qee0I/DwI5DHSCi3p5fsl6FyLGArrnDz3ox9qZr5Qc=.ed25519) \n\nI'd really like to get this issue confirmed either way. If you have a reproducible test case or could post your config, that would be super helpful. For example, if you're using \"noauth\" with the interface scoped to the network then it sounds like that would cause the issue you're describing. From the ssb-ws readme:\n\n> ## noauth\n>\n>given the flexibility of multiserver, you may want to run\nthis with noauth config locally. However this is ***not recommended***\nuntil ssb-ws prevents [dns rebinding attacks](https://medium.com/@brannondorsey/attacking-private-networks-from-the-internet-with-dns-rebinding-ea7098a2d325)\nand websocket connections from locally open websites.\n>\n>If used with a [secure transport](https://github.com/auditdrivencrypto/secret-handshake),\nthat authenticates the client `\"transport\": \"shs\"`\nthen this is not a problem.",
    "mentions": [
      {
        "link": "@8Qee0I/DwI5DHSCi3p5fsl6FyLGArrnDz3ox9qZr5Qc=.ed25519",
        "name": "ev"
      }
    ]
  },
  "signature": "k74INiAsqC5ICEOQNNWeQ9XYkqGcVmD1hD1g9IsvGh5zZPH+NfXkVVlPUxKdS8wlOAqbpsXw2Lk6xoPcsmPhBg==.sig.ed25519"
}